# Python package
# Create and test a Python package on a specific Python version.
    
trigger:
- main

pool: Default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'whoami'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python 3.8'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'